# Generated by Django 5.2.6 on 2025-10-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='autor',
        ),
        migrations.AddField(
            model_name='producto',
            name='materia',
            field=models.CharField(default='General', max_length=200),
        ),
        migrations.AddField(
            model_name='producto',
            name='titulo',
            field=models.CharField(default='Ingresar', max_length=200),
            preserve_default=False,
        ),
    ]
